# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
############################## => INPUT => ##############################
# $ `brew install mysql@5.7` 🍺 
############################## => OUTPUT => #############################
# . . .
# mysql@5.7 is keg-only, which means it was not symlinked into /usr/local,
# because this is an alternate version of another formula.

# For compilers to find mysql@5.7 you may need to set:
#   export LDFLAGS="-L/usr/local/opt/mysql@5.7/lib"
#   export CPPFLAGS="-I/usr/local/opt/mysql@5.7/include"

# For pkg-config to find mysql@5.7 you may need to set:
#   export PKG_CONFIG_PATH="/usr/local/opt/mysql@5.7/lib/pkgconfig"

# To have launchd start mysql@5.7 now and restart at login:
#   brew services start mysql@5.7
# Or, if you don't want/need a background service you can just run:
#   /usr/local/opt/mysql@5.7/bin/mysql.server start
# ==> Summary
# 🍺  /usr/local/Cellar/mysql@5.7/5.7.32: 319 files, 234.4MB
# . . .
##########################################################################

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: rails_react_habits_development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: rails_react_habits_test

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: rails_react_habits_production
  username: rails_react_habits
  password: <%= ENV['HABITS_DATABASE_PASSWORD_PROD'] %>
  # url: <%= ENV['HABITS_DATABASE_URL_PROD'] %>
